source "testlib.exp"
source "testprotocol.exp"

namespace import testprot::*

set debug 0
set verbose 0
set prompt "_Resp.*"

spawn ./testprot_server

reset_passes_and_fails

set test "EchoInt"
set inParams [dict create]
dict set inParams i 100
dict set inParams i_arr 1 101
dict set inParams i_arr 2 -102
dict set inParams i_arr 3 103
dict set inParams s8 -100
dict set inParams s8_arr 1 101
dict set inParams s8_arr 2 -102
dict set inParams s8_arr 3 103
dict set inParams s16 100
dict set inParams s16_arr 1 101
dict set inParams s16_arr 2 -102
dict set inParams s16_arr 3 103
dict set inParams s32 -100
dict set inParams s32_arr 1 101
dict set inParams s32_arr 2 -102
dict set inParams s32_arr 3 103
dict set inParams s64 100
dict set inParams s64_arr 1 101
dict set inParams s64_arr 2 -102
dict set inParams s64_arr 3 103
dict set inParams u8 100
dict set inParams u8_arr 1 101
dict set inParams u8_arr 2 102
dict set inParams u8_arr 3 103
dict set inParams u16 100
dict set inParams u16_arr 1 101
dict set inParams u16_arr 2 102
dict set inParams u16_arr 3 103
dict set inParams u32 100
dict set inParams u32_arr 1 101
dict set inParams u32_arr 2 102
dict set inParams u32_arr 3 103
dict set inParams u64 100
dict set inParams u64_arr 1 101
dict set inParams u64_arr 2 102
dict set inParams u64_arr 3 103
set checkParams $inParams

TestEchoInt $inParams $checkParams
show_passes_and_fails

set test "EchoEnum"
set inParams [dict create]
dict set inParams se -1
dict set inParams se_arr 1 -1
dict set inParams se_arr 2 0
dict set inParams se_arr 3 1
dict set inParams se8 0
dict set inParams se8_arr 1 -1
dict set inParams se8_arr 2 0
dict set inParams se8_arr 3 1
dict set inParams se16 1
dict set inParams se16_arr 1 -1
dict set inParams se16_arr 2 0
dict set inParams se16_arr 3 1
dict set inParams se32 -1
dict set inParams se32_arr 1 -1
dict set inParams se32_arr 2 0
dict set inParams se32_arr 3 1
dict set inParams ue8 0
dict set inParams ue8_arr 1 0
dict set inParams ue8_arr 2 1
dict set inParams ue16 1
dict set inParams ue16_arr 1 0
dict set inParams ue16_arr 2 1
dict set inParams ue32 0
dict set inParams ue32_arr 1 0
dict set inParams ue32_arr 2 1
set checkParams $inParams

TestEchoEnum $inParams $checkParams
show_passes_and_fails
